### ISSUE TITLE
Seccion Servicios (Calcular IMC-PesoIdeal)

### ISSUE THREAD

**Issue by cintiabelenestrada** [cintiabelenestrada/Trabajo_Final_2023_Grupo45#4]
**Servicios:** Muestra un menú desplegable con diferentes opciones:

- [ ] **Calcular IMC** (índice de masa corporal): Se presenta una página donde se muestran todos los

registros de índice de masa corporal del usuario ordenados por fecha descendente, el usuario debe
ingresar previamente su código de usuario.
Se visualizan los datos del usuario y se permite ingresar el peso actual, un botón calcular IMC realizará
el cálculo y el registro del IMC, que se determina de la siguiente forma:
Peso en Kg, altura en metros.
Los datos del cálculo del índice de masa corporal se guardan en un Objeto de la clase
IndiceMasaCorporal, con los siguientes datos:

- Id
- Fecha imc
- Usuario
- estado

El método calcularImc() retorna el resultado: “Su IMC es 20 – Está en su peso normal”
El usuario puede medir su IMC a medida que avanza en su plan de cuidado y dieta.

- [ ] **Peso Ideal:** Se presenta una página donde se muestra el peso ideal del usuario en función de su

estatura y edad empleando la fórmula de Perrault
El usuario debe ingresar previamente su código de usuario para poder ver su peso ideal.

**Comment by JohnRM992** [comment]
Para la implementación de esta seccion se crea la siguiente rama:

tpfinal_issue4_seccion_servicios

Edito: Se finalizó esta sección utilizando otras ramas

**Comment by FedericoNicolasBurgos** [comment]
terminado
